server:
  port: 8083

spring:

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1
    validate-on-migrate: false
  application:
    name: appointment-service
  data:
    redis:
      url: ${REDIS_URL:redis://localhost:6379}
      timeout: 5000ms
  datasource:
    url: jdbc:mysql://localhost:3306/appointment_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: swarnika
    password: Swarnika@2026
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: false

logging:
  level:
    org.apache.kafka.clients.NetworkClient: ERROR
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    properties:
      spring.json.add.type.headers: true

app:
  kafka:
    topics:
      appointment-booked: swarnika.appointment.booked
  security:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: false
  instance:
    hostname: localhost
    instance-id: localhost:appointment-service:8083
    health-check-url-path: /actuator/health
    status-page-url-path: /actuator/health

springdoc:
  swagger-ui:
    path: /

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always


