package com.swarnikacare.iam.entity;

public enum Permission {
    PATIENT_VIEW,
    PATIENT_CREATE,
    PATIENT_UPDATE,

    APPOINTMENT_VIEW,
    APPOINTMENT_CREATE,
    APPOINTMENT_RESCHEDULE,
    APPOINTMENT_CANCEL,

    EHR_VIEW,
    EHR_WRITE,

    PRESCRIPTION_VIEW,
    PRESCRIPTION_CREATE,

    LAB_ORDER_CREATE,
    LAB_REPORT_VIEW,

    BILL_VIEW,

    ENCOUNTER_VIEW,
    ENCOUNTER_CREATE,
    ENCOUNTER_UPDATE,
    ENCOUNTER_COMPLETE,

    OPD_VIEW,
    OPD_CREATE,

    EMERGENCY_VIEW,
    EMERGENCY_CREATE,

    PATIENT_RELATIONSHIP_VIEW,
    PATIENT_RELATIONSHIP_CREATE,
    PATIENT_RELATIONSHIP_DELETE,

    USER_MANAGE,
    DOCTOR_MANAGE,
    STAFF_MANAGE,
    ROLE_MANAGE,
    HOSPITAL_MANAGE,
    AUDIT_VIEW,
    REPORT_VIEW
}
