CREATE TABLE encounters (
  id BIGINT NOT NULL AUTO_INCREMENT,
  encounter_number VARCHAR(30) NOT NULL,
  patient_id BIGINT NOT NULL,
  hospital_id BIGINT NOT NULL,
  department_id BIGINT NOT NULL,
  doctor_id BIGINT NULL,
  encounter_type ENUM('OPD','EMERGENCY','INPATIENT','FOLLOW_UP') NOT NULL,
  status ENUM('OPEN','IN_PROGRESS','COMPLETED','CANCELLED') NOT NULL DEFAULT 'OPEN',
  appointment_id BIGINT NULL,
  source ENUM('SCHEDULED','WALK_IN','EMERGENCY','REFERRAL') NOT NULL,
  chief_complaint VARCHAR(500) NULL,
  notes TEXT NULL,
  started_at DATETIME(6) NULL,
  ended_at DATETIME(6) NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  UNIQUE KEY uk_encounter_number (encounter_number),
  INDEX idx_enc_patient (patient_id),
  INDEX idx_enc_hospital (hospital_id),
  INDEX idx_enc_doctor (doctor_id),
  INDEX idx_enc_appointment (appointment_id),
  INDEX idx_enc_type (encounter_type),
  INDEX idx_enc_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
