-- Migration V3: Add Inpatient Admissions, Referrals, Persistent Queue Tokens, and Audit Logs

CREATE TABLE admissions (
    id BIGINT NOT NULL AUTO_INCREMENT,
    admission_number VARCHAR(64) NOT NULL,
    patient_id BIGINT NOT NULL,
    hospital_id BIGINT NOT NULL,
    department_id BIGINT NOT NULL,
    admitting_doctor_id BIGINT NOT NULL,
    admission_date DATE NOT NULL,
    admission_time TIME NOT NULL,
    admission_type ENUM('ELECTIVE', 'EMERGENCY', 'TRANSFER', 'DAYCARE') NOT NULL,
    status ENUM('REQUESTED', 'ADMITTED', 'DISCHARGED', 'CANCELLED') NOT NULL DEFAULT 'REQUESTED',
    ward_id BIGINT NULL,
    room_id BIGINT NULL,
    bed_id BIGINT NULL,
    initiating_staff_user_id VARCHAR(100) NULL,
    reason VARCHAR(500) NOT NULL,
    notes TEXT NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uk_admission_number (admission_number),
    INDEX idx_adm_patient (patient_id),
    INDEX idx_adm_hospital (hospital_id),
    INDEX idx_adm_doctor (admitting_doctor_id),
    INDEX idx_adm_status (status),
    INDEX idx_adm_bed (bed_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE referrals (
    id BIGINT NOT NULL AUTO_INCREMENT,
    referral_number VARCHAR(64) NOT NULL,
    patient_id BIGINT NOT NULL,
    hospital_id BIGINT NOT NULL,
    referring_doctor_id BIGINT NULL,
    from_department_id BIGINT NULL,
    target_hospital_id BIGINT NOT NULL,
    target_department_id BIGINT NOT NULL,
    target_doctor_id BIGINT NULL,
    referral_type ENUM('INTERNAL', 'EXTERNAL') NOT NULL DEFAULT 'INTERNAL',
    priority ENUM('ROUTINE', 'URGENT', 'EMERGENCY') NOT NULL DEFAULT 'ROUTINE',
    status ENUM('REQUESTED', 'ACKNOWLEDGED', 'SCHEDULED', 'COMPLETED', 'CANCELLED', 'REJECTED') NOT NULL DEFAULT 'REQUESTED',
    reason VARCHAR(500) NOT NULL,
    clinical_notes TEXT NULL,
    appointment_id BIGINT NULL,
    administrative_notes TEXT NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uk_referral_number (referral_number),
    INDEX idx_ref_patient (patient_id),
    INDEX idx_ref_hospital (hospital_id),
    INDEX idx_ref_target_dept (target_department_id),
    INDEX idx_ref_target_doc (target_doctor_id),
    INDEX idx_ref_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE queue_tokens (
    id BIGINT NOT NULL AUTO_INCREMENT,
    token_number VARCHAR(32) NOT NULL,
    sequence_number INT NOT NULL,
    hospital_id BIGINT NOT NULL,
    department_id BIGINT NOT NULL,
    doctor_id BIGINT NOT NULL,
    patient_id BIGINT NOT NULL,
    appointment_id BIGINT NULL,
    encounter_id BIGINT NULL,
    queue_date DATE NOT NULL,
    status ENUM('WAITING', 'CALLED', 'IN_SERVICE', 'COMPLETED', 'SKIPPED', 'CANCELLED') NOT NULL DEFAULT 'WAITING',
    priority ENUM('NORMAL', 'URGENT', 'EMERGENCY') NOT NULL DEFAULT 'NORMAL',
    called_at DATETIME(6) NULL,
    completed_at DATETIME(6) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uk_hospital_queue_date_token (hospital_id, queue_date, token_number),
    INDEX idx_qt_doctor_date (doctor_id, queue_date),
    INDEX idx_qt_hospital_date (hospital_id, queue_date),
    INDEX idx_qt_patient (patient_id),
    INDEX idx_qt_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE audit_logs (
    id BIGINT NOT NULL AUTO_INCREMENT,
    hospital_id BIGINT NOT NULL,
    actor_user_id VARCHAR(100) NOT NULL,
    actor_role VARCHAR(50) NOT NULL,
    action VARCHAR(100) NOT NULL,
    entity_type VARCHAR(50) NOT NULL,
    entity_id VARCHAR(100) NOT NULL,
    details TEXT NULL,
    timestamp DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    INDEX idx_al_hospital_time (hospital_id, timestamp),
    INDEX idx_al_actor (actor_user_id),
    INDEX idx_al_action (action)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
