UPDATE hospitals SET type = 'GENERAL_HOSPITAL' WHERE type = 'GENERAL';
UPDATE hospitals SET type = 'MULTI_SPECIALTY_HOSPITAL' WHERE type = 'MULTI_SPECIALTY';
UPDATE hospitals SET type = 'SUPER_SPECIALTY_HOSPITAL' WHERE type = 'SUPER_SPECIALTY';
UPDATE hospitals SET type = 'DAY_CLINIC' WHERE type = 'CLINIC';
